### ISSUE TITLE
Changed spacing

### ISSUE THREAD

**Issue by cokolwiek235** [LesFerch/WinSetView#63] opened 2023-03-19 16:37 UTC
Program also changes spacing between icons in folders.

Also medium icon size change option doesn't work.

**Comment by LesFerch** [comment] 2023-03-19 16:59
Much more details are needed, such as what folder(s) are affected. What drive are they on? Fixed, vs removable vs network volume are all important. Are you referring to a device view such as a phone or DLNA server? What Windows version are you running? Note that Windows 11 has some bugs that affect folder views.

Most importantly, provide screenshots. Just paste them here. A picture is worth a 1000 words.

Please note that if those were general issues, I would already know about them. There are thousands (probably tens of thousands) of users at this point.

**Comment by cokolwiek235** [comment] 2023-03-19 18:30
Hello,

Ok, It affects all local disk folders, didn't check lan or removable devices, but assume its the same. I am using Windows 10.

Screenshot 1: How it looks before using program.
Screenshot 2: How it looks after specifying medium icons no matter what size I type in there.
Screenshot 3. How it looks when only size is set using ctrl+mouse scroll.

![1](https://user-images.githubusercontent.com/53710693/226198944-fdfa9a24-2e55-40aa-98ad-c9f351797543.jpg)
![2](https://user-images.githubusercontent.com/53710693/226198947-0db8d636-8ee3-4d32-b19e-8bfa8d6fc8ba.jpg)
![3](https://user-images.githubusercontent.com/53710693/226198949-df8bf03c-e6e6-4f6f-b9ab-eeee95f0d57c.jpg)


I have changed spacing between icons using this reg key (Icon size is still big everywhere after using it, but I can use ctrl+mouse scroll to make them look ok at least in file explorer for all folders):

```Windows Registry Editor Version 5.00

;Created by Vishal Gupta for AskVG.com

[-HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags]

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell]
"KnownFolderDerivedFolderType"="{57807898-8C4F-4462-BB63-71042380B109}"
"SniffedFolderType"="Generic"
"FolderType"="NotSpecified"

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{5C4F28B5-F869-4E84-8E60-F11DB97C5CC7}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{5fa96407-7e77-483c-ac93-691d05850de8}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{7d49d726-3c21-4f05-99aa-fdc2c9474656}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{94d6ddcc-4a68-4175-a374-bd584a510b78}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{b3690e58-e961-423b-b687-386ebfd83239}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001
```

**Comment by LesFerch** [comment] 2023-03-19 19:18
In all my tests, medium is always medium with standard spacing. Below are two screenshots. The first one is bare bones Windows default and then I just selected Medium icons for C:\. The second is after running WinSetView with Medium icons [48] selected for "Global". They're the same.
![image](https://user-images.githubusercontent.com/79026235/226203375-f60d5663-1d55-42c8-8027-56756060930b.png)
![image](https://user-images.githubusercontent.com/79026235/226203383-f2850524-504a-4c19-bb60-b5e251818e57.png)

However, there is an issue with the custom icon size. If you also have the option **Use General Items view for connected devices** checked, then the custom size will only apply to folder types that are NOT type General items, such as Pictures, Music, Documents, Videos, and the Downloads root.

I will see if there is a possible fix for that. In the meantime, try again with that option unchecked.

![image](https://user-images.githubusercontent.com/79026235/226203624-4c963523-d923-445c-9962-1b44e2e9c4d4.png)

**Comment by LesFerch** [comment] 2023-03-19 19:20
Note, "connected devices" are things like phones and tablets. This setting has no effect on USB or network drives.

**Comment by cokolwiek235** [comment] 2023-03-19 19:41
Unchecking general items view worked for icon size problem. Thank you.
But there is still issue with the space between icons. I will try to investigate further to see what registry keys are involved to be sure.

**Comment by LesFerch** [comment] 2023-03-19 19:48
I'm getting standard spacing. Is there any chance you have some other software installed that could affect the view?

**Comment by cokolwiek235** [comment] 2023-03-19 20:00
Just couple of registry keys. I'm not sure anymore if one I posted earlier is responsible. I need to verify that.

**Comment by LesFerch** [comment] 2023-03-19 20:12
The only icon spacing registry values I can find are the ones for the Desktop in HKCU\Control Panel\Desktop\WindowMetrics. Those only affect the Desktop. I'm not aware of any icon spacing settings for folders. WinSetView only sets the icon size. Explorer figures out the spacing.

**Comment by cokolwiek235** [comment] 2023-03-19 20:57
There certainly is. And its in the registry key I have sent earlier. I'm not sure how it works, because I didn't made it, but it just does...

**Comment by cokolwiek235** [comment] 2023-03-19 21:17
On askvg it says:
```The registry script utilizes 3 DWORDs: FFlags, LogicalViewMode and Mode. We have set FFlags DWORD to 43000000 to disable auto-arrange and align to grid features. LogicalViewMode and Mode DWORDs are used to define folder view type. We can set LogicalViewMode to 1, 2, 3, 4 or 5 to set the folder view type to Details, Tiles, Icons, List or Content respectively. Similarly we can set Mode to 1, 2, 3, 4, 5, 6, 7 or 8 to set the folder view type to Medium icons, Small icons, List, Details, Thumbnails, Tiles, Thumbstrip (filmstrip) or Content respectively.```

So its:
"FFlags"=dword:43000000
"Mode"=dword:00000001
It changes spacing only if both of those are set.

Source: https://www.askvg.com/how-to-disable-full-row-select-feature-enable-column-header-in-all-views-and-enable-icon-reordering-in-windows-7-explorer/

**Comment by LesFerch** [comment] 2023-03-19 21:30
That's an align to grid setting. It's an old hold-over from when you could arrange icons in folders freely, as you can on the desktop. That setting still allows freely moving icons in folders, but their positions won't be saved. I've played with setting before, but never thought about how it might be affecting spacing. I'll take a look when I'm back at my desk.

**Comment by LesFerch** [comment] 2023-03-20 01:29
With the disable auto-arrange registry value set with medium icons, the horizontal spacing is unchanged. The vertical spacing is a little large, so fewer items fit in the same space. Is that what you want? I'm not seeing any advantage. Here's a screen shot. I captured it with the folder placement bar showing so you know I have that value set:
![image](https://user-images.githubusercontent.com/79026235/226226458-fe92caa0-6318-49cc-bf13-84ca1eddbb66.png)

**Comment by LesFerch** [comment] 2023-03-20 16:22
Unfortunately, the way those registry entries work, it would be very difficult to integrate support for those settings into the program. If there were an equivalent setting in the FolderTypes key, it would be no problem, but they're shell bags entries and, in order to reset the default views, all shell bags keys have to be cleared. Sorry, it's not doable.

The custom icon size bug is fixed in version 2.65. Thanks for bringing that to my attention.

**Comment by cokolwiek235** [comment] 2023-03-20 17:27
Alright, so I guess I will just remove the delete key part in my reg file and will use it after I run the settings in WinSetView. It works fine that way. What I needed from WinSetView was just list view in open/save dialogs. I have no idea how to set those everywhere without your tool.

I guess you could close it if you don't have anything more to add to this conversation.

Thank you :)

**Closed** 2023-03-20 18:06 UTC

**Comment by LesFerch** [comment] 2023-03-25 05:45
You may have already figured this out from the documentation, but just in case...

You can put your reg file inside WinSetView's **Appdata** folder and name it **WinSetViewCustom.reg**. Then it will be applied whenever you run WinSetView. I just tested it and confirmed the spacing resulted in "!Other Stuff!" fitting on one line with medium icons.

Out of curiosity, why use medium icons for those music folders when list view or small icons shows the full names on one line and fits more folders in less space?

**Comment by LesFerch** [comment] 2023-03-25 05:46
P.S. I enjoyed looking over your music collection. Lots of familar stuff there. A litte harder rocking than my current tastes, although there was a time I had a lot of those bands in my playlists. My current favorite bands are The War on Drugs (last three albums) and Nada Surf (esp. The Stars Are Indifferent to Astronomy), but I have lots of older stuff playing all the time: R.E.M., The Church (first five albums), Hoodoo Gurus, the list goes on... 

BTW, Brayan Adams should be Bryan Adams. Spotted that one right away since I'm Canadian. ;-)

**Comment by LesFerch** [comment] 2024-01-24 21:14
@cokolwiek235 I took another look at this and found that I could implement the option. If you download the latest version, you will find an option labelled **Legacy row and icon spacing** and when that is checked, another option labelled "\**Disable full row select**".

Please be note that this setting is not compatible with dark mode. That is, you will get black text on a the dark background. Maybe you already noticed that on your computer?
