### ISSUE TITLE
Uncheck all, Remember WinSetView and Explorer window size+pos, Copy+paste view settings, Easier way to rearrange columns, Dark theme

### ISSUE THREAD

**Issue by Owyn** [LesFerch/WinSetView#41] opened 2022-10-25 20:54 UTC
Use case: - I just want to manually edit settings for image search results (since you can't do that in win10 without apps or regedits)

Current situation: - I have to manually uncheck like 30+ checkboxes to do that

**Comment by Owyn** [comment] 2022-10-25 21:19
+ I just noticed that there's a problem - I can't uncheck "general" to set just search results... my time unchecking of 30+ items just got wasted :-(

**Comment by LesFerch** [comment] 2022-10-25 23:44
"General items" can be unchecked. Do you mean "Global"? If so, it doesn't have a check box because it doesn't need one. If you have unchecked everything, except "Pictures Search Results" then the settings for Global are going to do absolutely nothing.

So, go ahead and set "Pictures Search Results" with everything else unchecked and ignore "Global". You will get the result you seek. However, you are defeating most of the purpose of the program. Without setting defaults for all folder types, you are susceptible to getting reverted back to Windows defaults if something goes awry with a Windows update. If you set the defaults, and experience a situation like that, your folder views will revert to your preferred defaults.

**Comment by Owyn** [comment] 2022-10-26 11:02
> However, you are defeating most of the purpose of the program. 

Well, this is pretty much the only program which can do what I want (editing "picture search results" settings)

**Comment by Owyn** [comment] 2022-10-28 16:34
### > So, go ahead and set "Pictures Search Results" with everything else unchecked and ignore "Global". 

thx for the advice but... that wiped all my folder settings everywhere :-( even thought I unchecked everything except picture search results
even my saved explorer window size

**Comment by LesFerch** [comment] 2022-10-28 16:40
In order to set new defaults for any folder type, all individual per folder settings must be cleared. However, under the "Advanced" interface, there is a checkbox in the Options screen to "Keep Apply to Folders" settings. If checked, this will retain your defaults for the five major folder types.

You can restore your previous settings using the Restore button and try again with that option checked.

But seriously, it's easier to just set your preferred defaults using WinSetView.

**Comment by Owyn** [comment] 2022-10-28 16:47
> "Keep Apply to Folders" settings

I seriously wouldn't have guessed what it's for if not the explanation now... maybe rename it to what it actually does ("don't reset unchecked") and put a warning that everything will be RESET when you press "submit"?

> But seriously, it's easier to just set your preferred defaults using WinSetView.

In notepad it's even easier since I can copy-paste settings from one to another, e.g. from [videos] to [vidoes search results] etc

**Comment by Owyn** [comment] 2022-10-28 16:54
There's a "reset vies to win default" checkbox btw, and I did NOT check it so I thought... it wouldn't reset?

Why reset the explorer window size and position btw? can it maybe be kept somehow or carried over?

**Comment by LesFerch** [comment] 2022-10-28 16:54
It's named correctly. See the manual for details. It doesn't really work the way you're thinking even if the result is what you want. It's under "Advanced" for a reason (again see manual for details).

You wouldn't need to be editing the INI file if you use it as intended. Set all the defaults as you like for the major categories and then only uncheck Inherit to override a folder type (like your Pictures search results).

**Comment by Owyn** [comment] 2022-10-28 16:59
>  if you use it as intended.

Well, I want one view for pictures & videos & library, and other for documents & general & etc, and there's only one global setting, how else can I copy in groups if not with notepad? I'm trying to figure out how to use it as intended...

**Comment by LesFerch** [comment] 2022-10-28 17:00
Nope. The per folder settings are in the Bags/BagMRU registry keys. They're obscure, binary, weirdly indexed and prone to corruption. Those keys have to be cleared to reset any defaults. I spent hundreds of hours on this. If there were a more elegant way to do it, I would have found it.

**Comment by LesFerch** [comment] 2022-10-28 17:10
You would need to set approximately the same number of defaults as you would using File Explorer. That is, you would set your preferred view for Pictures and all the other Pictures type folders will inherit from there. Same for Videos and Documents.

It sounds like you want General to be the same as Documents, so set your Global setting to that preferred view and leave Inherit checked for General and Documents.

Since you want Pictures the same as Videos, that's one where you can save some clicking by editing the INI file 

Maybe, when I have some spare time, I'll add a "clone" button to copy settings from one folder type to another.

**Comment by Owyn** [comment] 2022-10-28 17:54
Cloning would be nice,

I had to look at the manual to find a way to rearrange details columns... but it seems impossible to put anything before filename tho because filename can't be unchecked - a simpler way to rearrange columns would be nice - e.g. drag & drop here maybe (or just a [left] \ [right] buttons to change order for column headers):
![изображение](https://user-images.githubusercontent.com/1309656/198699825-1f0d1f5b-34e7-4707-8d3e-ed3ef12361e2.png)

**Comment by LesFerch** [comment] 2022-10-29 04:45
Ahh, I hadn't considered that someone might want something other than Name as the first column. That's a pickle. Name is required (File Explorer also won't let you remove it) but it doesn't necessarily have to be the first column. I'm not sure what I can do for a fix. A column drag type interface, like File Explorer provides, is outside the scope of this project. Maybe in a future rewrite in C#, but not as an HTA. Left Right buttons would have to be under each column heading, so that's also really complicated to implement. I'll look into it and see what's feasible. Thanks for pointing out the deficiency.

**Comment by LesFerch** [comment] 2022-10-29 04:50
A quick fix may be to allow Name to be unchecked but require it to be checked before leaving that page. The problem with that idea is that a message box would be required and I really try to avoid adding messages because there are over 30 languages to support.

**Comment by Owyn** [comment] 2022-10-29 11:26
> Left Right buttons would have to be under each column heading

Like this then perhaps? 

see my well-drawn clickable red arrows 
![image](https://user-images.githubusercontent.com/1309656/198828781-020d4b25-07cf-4977-a441-215ecee6e9ef.png)

**Comment by Dhyfer1** [comment] 2022-11-02 02:54
> ![image](https://user-images.githubusercontent.com/1309656/198828781-020d4b25-07cf-4977-a441-215ecee6e9ef.png)

@Owyn I'm using the latest version, but in WinSetView I don't see any option to have it with dark theme. How come yours appears like this?

**Comment by Owyn** [comment] 2022-11-02 12:18
@Dhyfer1 windows contrast theme does that for all apps

**Comment by Dhyfer1** [comment] 2022-11-02 12:54
> @Dhyfer1 windows contrast theme does that for all apps

Ok, I understand. I always leave the default contrast values, but it looks good winsetview with dark theme.

@LesFerch can you create a dark theme for winsetview?

**Comment by LesFerch** [comment] 2022-11-02 13:30
> @LesFerch can you create a dark theme for winsetview?
@Dhyfer1 I think so. I'll put that on the To Do list.

**Comment by LesFerch** [comment] 2022-11-18 04:46
There are actually several requests in this issue thread, many of which will be addressed in version 2.50 (I'll probably release a Beta first)...

1) **Uncheck all button**: This is actually very easy to implement. However, I think the request was based on the idea that the views for any unchecked folder types would not be affected. If that were true, then I could see the value in unchecking everything expect the view you want to update, but, as previously discussed, it doesn't work that way. In order to effectively update any view, the individual folder view settings must be cleared.

I did some testing of your particular scenario to see what would happen if I added an option to NOT clear the current per-folder settings (i.e. don't delete the Bags/BagMRU keys). The results were... unpredictable. For example, I did a search within Pictures and set the search results view to List and then did the same to a C:\Photots folder. I then updated the default view for Pictures Search Results to Details with a specific set of column headings, but left the Bags/BagMRU keys intact. A search on the C:\Photos folder resulted in the new view being displayed (which actually I didn't expect) but a search on Pictures resulted in a Details view with the Windows default column headings for General items (weird). Running the same test with the usual steps (i.e. clear the Bags/BagMRU keys) the Pictures Search Results were the correct new default view everywhere.

So, that was a long winded way of saying that I could add an uncheck all button, but I think it's not really useful and may lead users to incorrectly assume that they can "protect" existing views that way.

2) **Why reset the explorer window size and position?** Since that's also stored with the Bags key, it gets whacked along with the per-folder settings. But I can just backup and restore the subkey where the size and position is saved (HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell), apparently, without breaking anything. This will be in 2.50.

3) **Cloning would be nice**: Working on it.

4) **Rearrange details columns**: I've implemented a little pop-up drag sort for the column headings for version 2.50. This greatly reduces the clicking required to make rearrange columns and lets you select any order (i.e. Name does not have to be first).

5) **@Dhyfer1 Dark theme**: So far, I've added a selector to choose a Light or Dark theme. I'm working on extending this to make the theme file external and user-editable (so you can edit existing themes or add your own).

**Comment by Dhyfer1** [comment] 2022-11-21 23:45
> **@Dhyfer1 Dark theme**: So far, I've added a selector to choose a Light or Dark theme. I'm working on extending this to make the theme file external and user-editable (so you can edit existing themes or add your own).

Great, I hope the next version will have the theme selector you mention. 😊

By the way, when the file explorer is in the Details view, by default the text in the column headers is aligned to the left. Can you make winsetview able to change the position of the text to leave it in the center?

**Comment by LesFerch** [comment] 2022-11-22 03:01
> By the way, when the file explorer is in the Details view, by default the text in the column headers is aligned to the left. Can you make winsetview able to change the position of the text to leave it in the center?

AFAIK, File Explorer provides no method (controls or registry settings) to change the column headers to center or right justified. If I missed something, please let me know. Thanks.

**Comment by Dhyfer1** [comment] 2022-11-24 23:06
Well, it was just an idea, I don't know either. And I don't know if [this](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.columnheader.textalign?view=netframework-4.8) can be useful, however I will keep looking to see if I can find something else.

**Comment by LesFerch** [comment] 2022-12-09 08:01
WinSetView 2.50 beta is now available to [download](https://github.com/LesFerch/WinSetView/tree/beta). It includes the following improvements:

**Uncheck/Recheck all button**: Added to the Advanced interface as it could be useful for someone who wants to keep the majority of the folder type views set to Windows defaults.

**Remember File Explorer's Size and Position**: The File Explorer window size and position is now retained.

**Remember WinSetView's Size and Position**: The WinSetView window size and position is now remembered. There is also now a "Re-center" button to center the app on the primary display.

**Copy and Paste Folder View Settings**: There are now Copy and Paste buttons for easy copying of view settings from one folder type to another.

**Column Rearranging Feature**: There is now an easy drag sort dialog for rearranging column headings.

**Dark Theme**: There's now an extendable Theme menu with light and dark themes.

**More Granular File Dialog View Settings**: Separate views for File Open/Save dialogs can now be set on a per folder type basis.

**Note**: The built-in **Help** button will bring up the web page for the released (i.e. older) version. Go to the GitHub beta branch to see the updated manual, or click the [link](https://github.com/LesFerch/WinSetView/blob/beta/Manual.md).

I expect to move this beta to full release pretty quickly, but would like to get some feedback to ensure everything is okay. There are a lot of code changes in this update.

**Comment by LesFerch** [comment] 2022-12-09 08:07
@Dhyfer1 and @Owyn please try the new beta (see message above) and let me know how it goes. Thanks.

**Comment by Owyn** [comment] 2022-12-09 10:55
@LasFerch
I clicked "Options" and it's empty
![image](https://user-images.githubusercontent.com/1309656/206685777-ba6ce254-1f49-4146-817b-f27901b9a5d0.png)
Same for individual options
![image](https://user-images.githubusercontent.com/1309656/206686108-e0e14d53-9b01-4845-848b-106a080442a6.png)
same for change column order
![image](https://user-images.githubusercontent.com/1309656/206686188-c0f2e7e7-c8c6-4216-9348-de88869688b2.png)


copy - paste works, it's nice

also, language,fonts, theme settings aren't saved and are reset each program start

**Comment by LesFerch** [comment] 2022-12-09 12:15
That means Modal.hta is missing. How did you download? I just tested the [download link](https://github.com/LesFerch/WinSetView/archive/refs/heads/beta.zip) I provided and it's complete and works fine.

Re.  language, fonts, theme setting: Those settings are all stored in the INI file which is only updated when you click Submit or use Save Settings. The window size and position is saved automatically to the registry, so that it's not a portable setting (since we can't count on screen coordinates being the same on another machine, especially when multiple monitors are involved).

**Comment by Owyn** [comment] 2022-12-09 12:18
Modal.hta is there in AppParts folder 
![image](https://user-images.githubusercontent.com/1309656/206700846-24d5efd9-222d-436e-bc6d-c6a95e086254.png)

I just downloaded your archive and extracted everything from it to the old WinSetView folder with replace

**Comment by LesFerch** [comment] 2022-12-09 13:09
Right. If Modal.hta were missing, the dialog wouldn't even have a title. This is bizarre. I can't imagine what's causing this behavior. Maybe something to do with your high contrast theme. But then, the dialog isn't even sized correctly, which indicates that there are no elements at all in the dialog. This makes no sense. Do you have any other machine (even a VM) to test on? Maybe if it works one place, we can figure out what's different that's breaking it.

**Comment by LesFerch** [comment] 2022-12-09 13:27
Nothing to do with high contrast. Tested that on Windows 10 and 11. Running out of ideas. What happens when you double-click Modal.hta? It should display this:
![image](https://user-images.githubusercontent.com/79026235/206712715-0d808f2a-d3ab-4466-9637-3fcddf2dbd57.png)

**Comment by Owyn** [comment] 2022-12-09 13:30
Here I switched off high contrast to test it, same result:
![image](https://user-images.githubusercontent.com/1309656/206711126-db258084-e7a6-45cf-9949-ac5ab95ac40e.png)

I just have one machine with no VMs

modal.hta:
![image](https://user-images.githubusercontent.com/1309656/206713285-c4bcb77e-bbef-4d73-adce-c6be31384243.png)

**Comment by LesFerch** [comment] 2022-12-09 13:37
Font, font size, and a scale factor is passed to the dialog. I can see you just have the default font and size, so that leaves scale. What is your computer's screen scaling set to?

**Comment by Owyn** [comment] 2022-12-09 13:38
> Font, font size, and a scale factor is passed to the dialog. I can see you just have the default font and size, so that leaves scale. What is your computer's screen scaling set to?

125% for text and 125% for all elements

**Comment by LesFerch** [comment] 2022-12-09 13:47
Nothing unusual there. I already tested with 125% and 150% settings. I was worried about something more extreme like 300% on an 8K monitor (which should still work just fine). I'm at a loss here. Windows 10 I presume? Multiple monitors?

**Comment by Owyn** [comment] 2022-12-09 13:51
Windows 10 22H2 single 1080p (16:10) monitor

Maybe just don't use pop-ups and show everything in original window? (as for columns for example):
![image](https://user-images.githubusercontent.com/1309656/206717159-335f2711-005e-4425-94e5-3a6f794c796c.png)

**Comment by LesFerch** [comment] 2022-12-09 14:10
The same window could work ok for the file dialog view options (with dozens f hours of work) but would be pretty awful for the column rearranging (blank the screen, show rearrange dialog, redisplay screen). There's got to be some fix for this. Maybe some debugging code in Modal.hta will tell us something. Oh, I wish I was sitting in front of your computer, I love a challenge, but it's painful doing it step by step remotely (especially when it involves a lot of trial and error).

**Comment by LesFerch** [comment] 2022-12-09 14:26
Let's find out if this is a machine or user profile issue. Please test with another local user account, preferably a newly created account that just has default settings. The account doesn't need to be administrator, but it would probably be more convenient if it is (i.e. easier access to the same files).

**Comment by Owyn** [comment] 2022-12-09 14:42
I tried it on my GUEST account - said access denied on line 83 "getObject" and didn't run at all 🤷🏻

**Comment by LesFerch** [comment] 2022-12-09 14:56
Your Guest account appears to be more locked down than a standard user. Line 83 sets up an object to read registry values. WinSetView does work with a standard (i.e. non-administrator) user. I just tested the 2.50 beta to be sure and, yup, still works for a standard user on my machines.

**Comment by LesFerch** [comment] 2022-12-09 14:58
Is your Windows 10 22H2 Home or Pro? If Pro, there may be group policies involved in all this.

**Comment by Owyn** [comment] 2022-12-09 15:11
Pro, perhaps it's group policies or something alike cuz a new user account works fine

btw, an option window with a single option inside is kinda ridiculous... (separate views for open\save dialogues) - just make a checkbox there with a tooltip for that

**Comment by LesFerch** [comment] 2022-12-09 15:37
Ahh, good to hear it's something in your profile. It would be nice to know what that "something" is, so I'd love to find a way to replicate the issue. Maybe if I could get an export of your user profile policy settings or maybe an entire copy of your profile? If you find a way to replicate the issue on another account, then maybe that will narrow it down to something you can send to me.

And yes, I know the one option is a bit silly, but I tried all kinds of layouts to have it on the main screen and it was just too cluttered (and potentially confusing for the less-technical users). I've learned from feedback that keeping as little as possible on the main screen is important. That's why "Load Settings" and "Save Settings" are under Advanced. Users were unclear regarding settings in an INI file versus folder view settings applied to the registry. And, hey, someday there may be a second option in that menu. 😉

**Comment by LesFerch** [comment] 2022-12-09 15:47
BTW, I noticed some minor display issues with the high contrast modes. The background colour for hover does not change (makes the column rearranging tool a little less user-friendly) and the path items, that are supposed to be in blue, are not. I'll see f I can find some workarounds for these issues. Not sure if I can detect the high contrast theme. Maybe it's a registry value I can read...

**Comment by LesFerch** [comment] 2022-12-09 16:34
Hmm, those instructions use the files Security.csv and Audit.ini. Your zip file contains Registry.pol and comment.cmtx. 🤔

**Comment by Owyn** [comment] 2022-12-09 16:37
It's from the 1st step which is for group policies, extract to your:
![image](https://user-images.githubusercontent.com/1309656/206749096-b1112d58-5820-4cd3-bf91-c39648795607.png)

**Comment by LesFerch** [comment] 2022-12-09 17:00
Ahh. thanks. It's been about a dozen years since I did anything with group policies. I don't have a Windows 10 Pro machine set up at the moment, so I copied the files to Windows 10 Home and Windows 11 Pro machines and rebooted. Nothing changed. WinSetView still worked fine on both machines.

**Comment by LesFerch** [comment] 2022-12-09 17:16
Agreed. Nothing there of interest:
![image](https://user-images.githubusercontent.com/79026235/206756940-59a49b92-bb5c-4788-a8e4-1000ceaea84a.png)

**Comment by LesFerch** [comment] 2022-12-09 17:17
It has to be a registry setting in HKCU. You could export the entire HKCU key and I'll import it into a test machine. Hopefully that will produce the problem.

**Comment by LesFerch** [comment] 2022-12-09 17:25
Also, did you check the folder C:\Windows\System32\GroupPolicyUsers?

**Comment by Owyn** [comment] 2022-12-09 17:55
that folder is empty for me

what email can I send you my HKCU?

**Comment by LesFerch** [comment] 2022-12-09 18:23
Use the gmail address that's in the manual. Thanks!

**Comment by LesFerch** [comment] 2022-12-10 18:31
Thanks for the HKCU reg file. I narrowed it down to this:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\International]
"sDecimal"=","
"LocaleName"="en-US"
```
It seems MSHTML has some issue with the combination of **en-US** format with a comma decimal separator. If you change the separator to a period, it's fine. It's also fine with the combination of **en-UK** and a comma decimal separator. I will try to find a way to make the dialog work regardless of these settings. In the meantime, I recommend either changing the format to **en-UK** or the decimal separator to a **period**.

**Comment by Dhyfer1** [comment] 2022-12-10 21:43
Hi. Thank you very much for the beta version, in my case it works without problem. I just use WinSetView to change the order of the columns from this order: **Name, Date modified, Type and Size** to this order **Name, Type, Size and Date modified**, and order by ascending type with the Global option and Details view, except for the Pictures folder.

I like that you have integrated themes, and I like more that I can edit them or add more themes. And my question regarding the themes is: when I open the Themes.ini file I see that some themes, for example the Dark 1 theme, some colors appear in hex format and other colors appear as they are named, for example DeepSkyBlue, or GhostWhite or PaleGreen etc. Where did you get these names from?

I hope that in a next update of beta version, when I click on the Help button, it will take me to the beta version documentation. That's all.

**Comment by LesFerch** [comment] 2022-12-10 22:58
https://www.w3schools.com/tags/ref_colornames.asp

I was planning to add a beta check to the Help button to go to the beta docs. Will do that soon.

**Comment by Dhyfer1** [comment] 2022-12-10 23:13
> https://www.w3schools.com/tags/ref_colornames.asp

Interesting, thanks for the link

> I was planning to add a beta check to the Help button to go to the beta docs. Will do that soon.

Very good, I would also like you to add an option for WinSetView to check for updates and if it finds a new version, then it can auto-update itself.

**Comment by LesFerch** [comment] 2022-12-11 03:35
> I would also like you to add an option for WinSetView to check for updates and if it finds a new version, then it can auto-update itself.

I'm thinking along the lines of adding a non-intrusive indicator on screen that lets your know there is a newer version available.

Auto-update requires a lot of careful checks and contingencies. For example, what if you're running from read-only media? There's a lot that can go wrong and every error message has to be translated to 30+ languages. I know it's standard fare for most apps, but most apps are English only and are written in languages where you can probably just plug in a well-debugged auto-update library. Someday I may rewrite the whole thing in something like C#/WinUI to Microsoft Store standards with auto update and so forth. That will probably take me something like two years (if I have the motivation). In the meantime, I think an update indicator is the best I can do. At least the download link is right there via the Help button.

Thought... The high quality of some of the free apps out there sometimes makes us take things for granted. I do what I can. I hope it's enough.

**Comment by Owyn** [comment] 2022-12-11 08:58
I think many popular apps still just say that there's a new version out there, go get it, and that's it for auto...

btw, about drag-n-drop - why is it vertical? can it be made horizontal like it is originally shown in the windows explorer perhaps?


> en-US format with a comma decimal separator. 

That's a surprising find... I didn't change any regional settings, that's just how win10 configured my initial account, and what's more weird - is that it configures all accounts after in a different way - cuz a new account I tested on had WinSetView working fine - so it wasn't a comma+en-US there by default

**Comment by LesFerch** [comment] 2022-12-11 14:41
> I think many popular apps still just say that there's a new version out there, go get it, and that's it for auto...

Agreed. Thanks.

> about drag-n-drop - why is it vertical? can it be made horizontal like it is originally shown in the windows explorer perhaps?

Of course, I wanted to do that, but it's much more complex. The headings may be wider than the window, requiring horizontal scrolling, but the biggest challenge is that the column widths vary, so, as the pointer hovers over the next column they are swapped and your pointer can end up over the previous item causing an immediate swap back. That makes for crazy flickering as you drag the items. The only somewhat easy workaround is to temporarily make all the columns a fixed width with the text cut off on some of them. It was all too much programming work. The vertical sort is dead simple.

> That's a surprising find... I didn't change any regional settings...

I knew it was going to be something unusual, but if it happened once, it will happen again, so I'll work to find a fix.

**Comment by Dhyfer1** [comment] 2022-12-11 21:40
> I'm thinking along the lines of adding a non-intrusive indicator on screen that lets your know there is a newer version available.

Oh, that's ok. Applications like Gimp cannot auto-update, but with a pop-up window Gimp indicates that a new version is available with a link to the new version to download from the browser.

**Comment by LesFerch** [comment] 2022-12-12 17:23
@Dhyfer1 and @Owyn [Version 2.51 Beta](https://github.com/LesFerch/WinSetView/blob/beta/README.md) is now available.

**Comment by LesFerch** [comment] 2022-12-15 06:11
@Dhyfer1 and @Owyn [Version 2.52](https://lesferch.github.io/WinSetView/) is now available and the beta branch has been removed.

**Closed by LesFerch** 2022-12-15 06:11 UTC
