### ISSUE TITLE
Fully portable version

### ISSUE THREAD

**Issue by SumatraPeter** [LesFerch/WinSetView#9] opened 2021-04-19 21:23 UTC
The app settings, registry backups etc. are currently stored in `AppData\Roaming\WinSetView` if I'm not mistaken. It would be great if the entire thing was to be self-contained in a single folder that could be stored in any location.

**Comment by LesFerch** [comment] 2021-04-20 03:51
That brings into play Windows programming standards and user rights. Regular (non-admin) users cannot write everywhere. Using the Roaming folder means it works for all users (and moves with users in an Active Directory domain). Off the top of my head, I could have it write everything to a folder at the same location as the script and go to the Roaming folder if the user has no write access. But...that may be a confusing change. I might make it a switch, so you can have it work one way or the other. Have to think about it...

**Comment by Gitoffthelawn** [comment] 2021-04-20 08:29
> Off the top of my head, I could have it write everything to a folder at the same location as the script and go to the Roaming folder if the user has no write access.

👍🏾

**Comment by SumatraPeter** [comment] 2021-04-20 11:26
> Off the top of my head, I could have it write everything to a folder at the same location as the script and go to the Roaming folder if the user has no write access.

This would be ideal. With everything in a single folder it'll be easy to more around, backup the entire thing etc. Thanks for considering it.

**Comment by GitHubRulesOK** [comment] 2021-04-22 01:38
For Portable use just move line 68 down below MyPath to 71 and replace the one "%appdata%" to MyPath it should then trickle down
![image](https://user-images.githubusercontent.com/12754913/115642448-e7491f80-a312-11eb-8dd1-4ffb9bf9350e.png)

Sorry I cant test it on this old machine as it complains power-script is not new enough :-) but will test more thoroughly tomorrow

**Comment by GitHubRulesOK** [comment] 2021-04-22 12:26
I encounter several inter related issues here
As a portable user I may be faced with a win 7 that does not have a moder powershell thus the ps component is rejected
On a Win 10 as a lowly user I have to first invoke
`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`
at least then the ps script should work ( and indead it does from the command line as permitted)
HOWEVER it will not run from the HTA (I see a flash of red text on the blue background)

1) is there a way to trap that message ?
2) All should be well with the script as standalone it writes  a backup.reg to the modified appdata dir (as intended)

I suspect it is UAC interference in running .ps1 from HTA but need to somehow trap that instant output at running in real time 
Any ideas ?

**Comment by LesFerch** [comment] 2021-04-22 12:36
I'll do some testing. Maybe in the HTA change...

CmdLine = "Powershell.exe -ExecutionPolicy Bypass " & Chr(34) & MyPath &
"WinSetView.ps1" & Chr(34) & " " & Params
to...
CmdLine = "Powershell.exe -ExecutionPolicy RemoteSigned -Scope CurrentUser"
& Chr(34) & MyPath & "WinSetView.ps1" & Chr(34) & " " & Params

**Comment by GitHubRulesOK** [comment] 2021-04-22 12:56
Thanks but that took slightly longer to run but the message flashes and exits too quick as far as I could tell in the first few words it said scope but thats all I saw in that instant HOWEVER it gave me the needed clue to add -noexit and now I see

-Scope : The term '-Scope' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -Scope CurrentUserc:\users\k\downloads\winsetview-main (1)\winsetview ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (-Scope:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by GitHubRulesOK** [comment] 2021-04-22 13:06
ok removing scope but keeping -noexit I now see the problem is a space in the script path so need to look closer at "quo ting"

**Comment by GitHubRulesOK** [comment] 2021-04-22 13:15
Bingo (so far) with -noexit in this line it seems to flow
using CmdLine = "Powershell.exe  -ExecutionPolicy RemoteSigned " & Chr(34) & ".\WinSetView.ps1" & Chr(34) & " " & Params
![image](https://user-images.githubusercontent.com/12754913/115719894-70dd0980-a374-11eb-9eeb-08ce593b8da3.png)

**Comment by LesFerch** [comment] 2021-04-22 13:17
I see I made a typo:

CmdLine = "Powershell.exe -ExecutionPolicy RemoteSigned -Scope CurrentUser"
& Chr(34) & MyPath & "WinSetView.ps1" & Chr(34) & " " & Params

should be:

CmdLine = "Powershell.exe -ExecutionPolicy RemoteSigned -Scope CurrentUser
" & Chr(34) & MyPath & "WinSetView.ps1" & Chr(34) & " " & Params

**Comment by LesFerch** [comment] 2021-04-22 13:27
CmdLine = "Powershell.exe -ExecutionPolicy RemoteSigned " & Chr(34) &
".\WinSetView.ps1" & Chr(34) & " " & Params

I'll do more testing, but that seems to be the way to go. The -noexit
leaves the console screen up after execution - not sure I want to do that.
Ideally, the console would stay open only if an error occurred.

**Comment by GitHubRulesOK** [comment] 2021-04-22 13:33
I added the pause (not needed when working) to see the result and agree the -noexit was just for the troubleshooting

my "portable" scripting.cmd is minimal and comspec should not be needed since its just during testing to force hta and ps to run in a common shell

set appdata=%~dp0
"%ComSpec%" /d /k "%~dp0WinSetView.hta"

**Comment by LesFerch** [comment] 2021-04-22 13:50
I need to recreate the error before changing the execution policy. From
what I've read, -bypass should work for all users. I just tested with a
standard (non-admin) user on Windows 10 and it worked fine with the -bypass
policy (i.e. no change to the script). When you tested with a standard
user, had you made any other changes? Where is the script located? In my
testing, I was running it from a C:\WinSetView, which is a location where a
standard user has write access, but since I haven't changed anything for
portable configuration yet, all writes would have been to Temp and Appdata.
Any details you can give me to recreate the error would be much
appreciated. Thanks.

Les

**Comment by GitHubRulesOK** [comment] 2021-04-22 14:27
If I reset to the published hta and ps in a directory with space and brackets (yes I now its NOT recommended but not uncommon) and set user access back to default (undefined) HTA appear to be working as designed but PS flashes red on blue

adding just -noexit into the PS call from HTA now stops to show the space is the problem (not UAC)

modifying to  

 CmdLine = "Powershell.exe -ExecutionPolicy Bypass " & Chr(34) & ".\WinSetView.ps1" & Chr(34) & " " & Params

works via cmd from that location pre-set as appdata or double click hta for normal user appdata use

thus it is the launch dir is the issue (surprised it has not been raised before?)

**Comment by LesFerch** [comment] 2021-04-22 14:46
Ahh, thank you! You are the first to report that issue. Checking execution
with spaces in the path (both script directory and user data) was on my
mental ToDo list. Probably should have written down that ToDo list. ;-)
 While I'm at it, I should check execution when there's an "&" in the path.
Windows allows that character, but it wreaks havoc with batch files. Maybe
not an issue with VBscript and Powershell, but I better check anyhow.

Regarding making it portable... I'm working on it. I have to figure out how
to handle existing data (i.e. abandon or migrate) and I have to verify if
backup reg files are really useful on another machine. I'm pretty sure
Streams/Defaults is very portable. Not so sure about BagMRU/Bags keys. If
they are not portable, I probably should have put the backup data in Local
instead of Roaming. Minor thing, but I might as well be thorough.

**Comment by GitHubRulesOK** [comment] 2021-04-22 15:19
Finally I think this may work with the HTA modified to accept spaces

Portable.cmd placed in the working dir with hta and ps1

`set appdata=%~dp0 & set appdata=%appdata:~0,-1%& "%~dp0WinSetView.hta"`

**Comment by LesFerch** [comment] 2021-04-22 21:26
I was scratching my head over the space in the path issue since the path is
quoted. But it turns out that I have to use the -File parameter to ensure
Powershell takes that item as the file path. Like this...

CmdLine = "Powershell.exe -ExecutionPolicy Bypass -File " & Chr(34) &
MyPath & "WinSetView.ps1" & Chr(34) & " " & Params

Whie it SHOULD always work with .\ like you suggested...

CmdLine = "Powershell.exe -ExecutionPolicy Bypass " & Chr(34) &
".\WinSetView.ps1" & Chr(34) & " " & Params

I shy away from that format because it has burned me in the past. Just
today I was testing a .\ path with Powershell. It worked fine when I
right-clicked the file and selected "Run with Powershell", but failed when
I ran the script from the console (the path resolved to System32).

**Comment by GitHubRulesOK** [comment] 2021-04-22 21:45
> the path resolved to System32

Yes that a newer twist than I recollect from yore (but my old dog memory is failing,, thus I like to keep old tricks like this active)
MS ? seem to default any unqualified CMD.exe to an absolute home location (%comspec%) ant it is a bugger to keep telling it not to

**Comment by LesFerch** [comment] 2021-04-23 01:42
Oops. -File does not work. It passes the filename properly, but causes the Params to be ignored. So, I'm going with ".\" for now. Anyone who downloaded from Main in the past 4 hours needs to redownload.

**Comment by GitHubRulesOK** [comment] 2021-04-23 01:45
@LesFerch 
**Something is broken by latest upload**

I am not getting good results (changes do not work)
I went back to win7 32bit pro admin user to check and with yesterdays hta all was fine (portable or not)
downloaded today's hta (now has the changed PS call )
and win 7 is not respecting my choice of column order

The reason I stepped back to 7 was because I was seeing poor results on win 10 as restricted user and wanted to double check

**Comment by LesFerch** [comment] 2021-04-23 02:01
Please download again. I replaced the broken HTA file just 20 minutes ago.

**Comment by LesFerch** [comment] 2021-04-23 03:30
The scripts have now been updated to a fully portable design as discussed above. Please download from Main. Thanks.

**Comment by GitHubRulesOK** [comment] 2021-04-23 15:51
THANKS All now seems to be working well 
I can drag and drop a presaved set running from a remote named drive and it will reconfigure the local restricted users layout no problem

No additions to systems folders (apart from normal prefetch etc ) /no additions to users appdata
so only question is how much out of necessity is altered in registry, but that's what the rollback options are for

**Comment by LesFerch** [comment] 2021-04-23 15:59
You're welcome and thanks for the help! I'll close this issue now.

**Closed by LesFerch** 2021-04-23 15:59 UTC

**Comment by LesFerch** [comment] 2021-07-04 02:06
WinSetView v2 is also fully portable.
